### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Ngotcode**

### CODE REVIEW

**Comment by Ngotcode** [comment]
Hi,


I have no luck trying to execute the run.py at home.  Even after removing the jcc-app from my computer and reinstalling everything and then “python run.py”
The ip address is correct but iterm2 gave me this error:




sqlalchemy.exc.OperationalError


OperationalError: (sqlite3.OperationalError) no such table: event [SQL: u'SELECT event.id AS event_id, event.date AS event_date, event.name AS event_name \nFROM event']








Thanks,



Teri
P.S. Since I am taking the R class tomorrow, I will not be able to make it to Friday’s noon session.  Talked to QingJun and she said she is working on the LDAP.

**Comment by ntj** [comment]
@Ngotcode , I think you need to run the two commands to migrate the database and it will work:

`export FLASK_APP=app/__init__.py`
`flask db upgrade`

**Comment by Ngotcode** [comment]
Wholly molly! It works!
Thanks!
Got to get back to R.
Have a good weekend

**Comment by ntj** [comment]
You, too.

**Pull request closed without merging**
